name: Build LaTeX document
on: [push]
jobs:
 build_latex:
  runs-on: ubuntu-latest
  steps:
   - name: Set up Git repository
     uses: actions/checkout@v4
   - name: Compile LaTeX document
     uses: xu-cheng/latex-action@v3
     with:
      working_directory: src
      root_file: main.tex
   - name: Rename PDF file
     run: mv src/main.pdf src/amw_20232024_project.pdf
   - name: Upload PDF file
     uses: actions/upload-artifact@v4
     with:
      name: Report in PDF
      path: src/amw_20232024_project.pdf
